import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../resources/styles/globals.scss";
import "../resources/styles/slider.scss";
import "../resources/styles/vars.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TI Assistant (RS)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
