use dioxus::prelude::*;

const TILE_0: Asset = asset!("/assets/images/map/tiles/0.webp");
const TILE_1: Asset = asset!("/assets/images/map/tiles/1.webp");
const TILE_2: Asset = asset!("/assets/images/map/tiles/2.webp");
const TILE_3: Asset = asset!("/assets/images/map/tiles/3.webp");
const TILE_4: Asset = asset!("/assets/images/map/tiles/4.webp");
const TILE_5: Asset = asset!("/assets/images/map/tiles/5.webp");
const TILE_6: Asset = asset!("/assets/images/map/tiles/6.webp");
const TILE_7: Asset = asset!("/assets/images/map/tiles/7.webp");
const TILE_8: Asset = asset!("/assets/images/map/tiles/8.webp");
const TILE_9: Asset = asset!("/assets/images/map/tiles/9.webp");
const TILE_10: Asset = asset!("/assets/images/map/tiles/10.webp");
const TILE_11: Asset = asset!("/assets/images/map/tiles/11.webp");
const TILE_12: Asset = asset!("/assets/images/map/tiles/12.webp");
const TILE_13: Asset = asset!("/assets/images/map/tiles/13.webp");
const TILE_14: Asset = asset!("/assets/images/map/tiles/14.webp");
const TILE_15: Asset = asset!("/assets/images/map/tiles/15.webp");
const TILE_16: Asset = asset!("/assets/images/map/tiles/16.webp");
const TILE_17: Asset = asset!("/assets/images/map/tiles/17.webp");
const TILE_18: Asset = asset!("/assets/images/map/tiles/18.webp");
const TILE_19: Asset = asset!("/assets/images/map/tiles/19.webp");
const TILE_20: Asset = asset!("/assets/images/map/tiles/20.webp");
const TILE_21: Asset = asset!("/assets/images/map/tiles/21.webp");
const TILE_22: Asset = asset!("/assets/images/map/tiles/22.webp");
const TILE_23: Asset = asset!("/assets/images/map/tiles/23.webp");
const TILE_24: Asset = asset!("/assets/images/map/tiles/24.webp");
const TILE_25: Asset = asset!("/assets/images/map/tiles/25.webp");
const TILE_26: Asset = asset!("/assets/images/map/tiles/26.webp");
const TILE_27: Asset = asset!("/assets/images/map/tiles/27.webp");
const TILE_28: Asset = asset!("/assets/images/map/tiles/28.webp");
const TILE_29: Asset = asset!("/assets/images/map/tiles/29.webp");
const TILE_30: Asset = asset!("/assets/images/map/tiles/30.webp");
const TILE_31: Asset = asset!("/assets/images/map/tiles/31.webp");
const TILE_32: Asset = asset!("/assets/images/map/tiles/32.webp");
const TILE_33: Asset = asset!("/assets/images/map/tiles/33.webp");
const TILE_34: Asset = asset!("/assets/images/map/tiles/34.webp");
const TILE_35: Asset = asset!("/assets/images/map/tiles/35.webp");
const TILE_36: Asset = asset!("/assets/images/map/tiles/36.webp");
const TILE_37: Asset = asset!("/assets/images/map/tiles/37.webp");
const TILE_38: Asset = asset!("/assets/images/map/tiles/38.webp");
const TILE_39: Asset = asset!("/assets/images/map/tiles/39.webp");
const TILE_40: Asset = asset!("/assets/images/map/tiles/40.webp");
const TILE_41: Asset = asset!("/assets/images/map/tiles/41.webp");
const TILE_42: Asset = asset!("/assets/images/map/tiles/42.webp");
const TILE_43: Asset = asset!("/assets/images/map/tiles/43.webp");
const TILE_44: Asset = asset!("/assets/images/map/tiles/44.webp");
const TILE_45: Asset = asset!("/assets/images/map/tiles/45.webp");
const TILE_46: Asset = asset!("/assets/images/map/tiles/46.webp");
const TILE_47: Asset = asset!("/assets/images/map/tiles/47.webp");
const TILE_48: Asset = asset!("/assets/images/map/tiles/48.webp");
const TILE_49: Asset = asset!("/assets/images/map/tiles/49.webp");
const TILE_50: Asset = asset!("/assets/images/map/tiles/50.webp");
const TILE_51: Asset = asset!("/assets/images/map/tiles/51.webp");
const TILE_52: Asset = asset!("/assets/images/map/tiles/52.webp");
const TILE_53: Asset = asset!("/assets/images/map/tiles/53.webp");
const TILE_54: Asset = asset!("/assets/images/map/tiles/54.webp");
const TILE_55: Asset = asset!("/assets/images/map/tiles/55.webp");
const TILE_56: Asset = asset!("/assets/images/map/tiles/56.webp");
const TILE_57: Asset = asset!("/assets/images/map/tiles/57.webp");
const TILE_58: Asset = asset!("/assets/images/map/tiles/58.webp");
const TILE_59: Asset = asset!("/assets/images/map/tiles/59.webp");
const TILE_60: Asset = asset!("/assets/images/map/tiles/60.webp");
const TILE_61: Asset = asset!("/assets/images/map/tiles/61.webp");
const TILE_62: Asset = asset!("/assets/images/map/tiles/62.webp");
const TILE_63: Asset = asset!("/assets/images/map/tiles/63.webp");
const TILE_64: Asset = asset!("/assets/images/map/tiles/64.webp");
const TILE_65: Asset = asset!("/assets/images/map/tiles/65.webp");
const TILE_66: Asset = asset!("/assets/images/map/tiles/66.webp");
const TILE_67: Asset = asset!("/assets/images/map/tiles/67.webp");
const TILE_68: Asset = asset!("/assets/images/map/tiles/68.webp");
const TILE_69: Asset = asset!("/assets/images/map/tiles/69.webp");
const TILE_70: Asset = asset!("/assets/images/map/tiles/70.webp");
const TILE_71: Asset = asset!("/assets/images/map/tiles/71.webp");
const TILE_72: Asset = asset!("/assets/images/map/tiles/72.webp");
const TILE_73: Asset = asset!("/assets/images/map/tiles/73.webp");
const TILE_74: Asset = asset!("/assets/images/map/tiles/74.webp");
const TILE_75: Asset = asset!("/assets/images/map/tiles/75.webp");
const TILE_76: Asset = asset!("/assets/images/map/tiles/76.webp");
const TILE_77: Asset = asset!("/assets/images/map/tiles/77.webp");
const TILE_78: Asset = asset!("/assets/images/map/tiles/78.webp");
const TILE_79: Asset = asset!("/assets/images/map/tiles/79.webp");
const TILE_80: Asset = asset!("/assets/images/map/tiles/80.webp");
const TILE_81: Asset = asset!("/assets/images/map/tiles/81.webp");
const TILE_82: Asset = asset!("/assets/images/map/tiles/82.webp");
const TILE_83A: Asset = asset!("/assets/images/map/tiles/83A.webp");
const TILE_83B: Asset = asset!("/assets/images/map/tiles/83B.webp");
const TILE_84A: Asset = asset!("/assets/images/map/tiles/84A.webp");
const TILE_84B: Asset = asset!("/assets/images/map/tiles/84B.webp");
const TILE_85A: Asset = asset!("/assets/images/map/tiles/85A.webp");
const TILE_85B: Asset = asset!("/assets/images/map/tiles/85B.webp");
const TILE_86A: Asset = asset!("/assets/images/map/tiles/86A.webp");
const TILE_86B: Asset = asset!("/assets/images/map/tiles/86B.webp");
const TILE_87A: Asset = asset!("/assets/images/map/tiles/87A.webp");
const TILE_87B: Asset = asset!("/assets/images/map/tiles/87B.webp");
const TILE_88A: Asset = asset!("/assets/images/map/tiles/88A.webp");
const TILE_88B: Asset = asset!("/assets/images/map/tiles/88B.webp");
const TILE_89A: Asset = asset!("/assets/images/map/tiles/89A.webp");
const TILE_89B: Asset = asset!("/assets/images/map/tiles/89B.webp");
const TILE_90A: Asset = asset!("/assets/images/map/tiles/90A.webp");
const TILE_90B: Asset = asset!("/assets/images/map/tiles/90B.webp");
const TILE_91A: Asset = asset!("/assets/images/map/tiles/91A.webp");
const TILE_91B: Asset = asset!("/assets/images/map/tiles/91B.webp");

/// Returns the image for the system with the provided id, if we have one.
pub fn get_tile_image(system_id: &str) -> Option<Asset> {
    match system_id {
        "0" => Some(TILE_0),
        "1" => Some(TILE_1),
        "2" => Some(TILE_2),
        "3" => Some(TILE_3),
        "4" => Some(TILE_4),
        "5" => Some(TILE_5),
        "6" => Some(TILE_6),
        "7" => Some(TILE_7),
        "8" => Some(TILE_8),
        "9" => Some(TILE_9),
        "10" => Some(TILE_10),
        "11" => Some(TILE_11),
        "12" => Some(TILE_12),
        "13" => Some(TILE_13),
        "14" => Some(TILE_14),
        "15" => Some(TILE_15),
        "16" => Some(TILE_16),
        "17" => Some(TILE_17),
        "18" => Some(TILE_18),
        "19" => Some(TILE_19),
        "20" => Some(TILE_20),
        "21" => Some(TILE_21),
        "22" => Some(TILE_22),
        "23" => Some(TILE_23),
        "24" => Some(TILE_24),
        "25" => Some(TILE_25),
        "26" => Some(TILE_26),
        "27" => Some(TILE_27),
        "28" => Some(TILE_28),
        "29" => Some(TILE_29),
        "30" => Some(TILE_30),
        "31" => Some(TILE_31),
        "32" => Some(TILE_32),
        "33" => Some(TILE_33),
        "34" => Some(TILE_34),
        "35" => Some(TILE_35),
        "36" => Some(TILE_36),
        "37" => Some(TILE_37),
        "38" => Some(TILE_38),
        "39" => Some(TILE_39),
        "40" => Some(TILE_40),
        "41" => Some(TILE_41),
        "42" => Some(TILE_42),
        "43" => Some(TILE_43),
        "44" => Some(TILE_44),
        "45" => Some(TILE_45),
        "46" => Some(TILE_46),
        "47" => Some(TILE_47),
        "48" => Some(TILE_48),
        "49" => Some(TILE_49),
        "50" => Some(TILE_50),
        "51" => Some(TILE_51),
        "52" => Some(TILE_52),
        "53" => Some(TILE_53),
        "54" => Some(TILE_54),
        "55" => Some(TILE_55),
        "56" => Some(TILE_56),
        "57" => Some(TILE_57),
        "58" => Some(TILE_58),
        "59" => Some(TILE_59),
        "60" => Some(TILE_60),
        "61" => Some(TILE_61),
        "62" => Some(TILE_62),
        "63" => Some(TILE_63),
        "64" => Some(TILE_64),
        "65" => Some(TILE_65),
        "66" => Some(TILE_66),
        "67" => Some(TILE_67),
        "68" => Some(TILE_68),
        "69" => Some(TILE_69),
        "70" => Some(TILE_70),
        "71" => Some(TILE_71),
        "72" => Some(TILE_72),
        "73" => Some(TILE_73),
        "74" => Some(TILE_74),
        "75" => Some(TILE_75),
        "76" => Some(TILE_76),
        "77" => Some(TILE_77),
        "78" => Some(TILE_78),
        "79" => Some(TILE_79),
        "80" => Some(TILE_80),
        "81" => Some(TILE_81),
        "82" => Some(TILE_82),
        "83A" => Some(TILE_83A),
        "83B" => Some(TILE_83B),
        "84A" => Some(TILE_84A),
        "84B" => Some(TILE_84B),
        "85A" => Some(TILE_85A),
        "85B" => Some(TILE_85B),
        "86A" => Some(TILE_86A),
        "86B" => Some(TILE_86B),
        "87A" => Some(TILE_87A),
        "87B" => Some(TILE_87B),
        "88A" => Some(TILE_88A),
        "88B" => Some(TILE_88B),
        "89A" => Some(TILE_89A),
        "89B" => Some(TILE_89B),
        "90A" => Some(TILE_90A),
        "90B" => Some(TILE_90B),
        "91A" => Some(TILE_91A),
        "91B" => Some(TILE_91B),
        _ => None,
    }
}
