CREATE TABLE game (
	id INTEGER PRIMARY KEY NOT NULL,
	name VARCHAR(128) NOT NULL
);

CREATE TABLE game_event (
	id SERIAL PRIMARY KEY,
	game_id INTEGER NOT NULL REFERENCES game(id),
	event JSONB NOT NULL
);

