#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Database communication for ti-helper.

/// The database tables and interactions with it.
pub mod db;
/// A unique id for a game.
pub mod game_id;
/// Queries to interact with the DB.
pub mod queries;
/// Autogenerated diesel schema file.
#[allow(missing_docs)]
pub mod schema;
