// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionCardProgress } from "./ActionCardProgress";
import type { FrontierCardProgress } from "./FrontierCardProgress";
import type { RelicProgress } from "./RelicProgress";
import type { StrategicProgress } from "./StrategicProgress";
import type { TacticalProgress } from "./TacticalProgress";

export type ActionPhaseProgress = { "t": "Strategic" } & StrategicProgress | { "t": "Tactical" } & TacticalProgress | { "t": "ActionCard" } & ActionCardProgress | { "t": "FrontierCard" } & FrontierCardProgress | { "t": "Relic" } & RelicProgress;