// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionCard } from "./ActionCard";

export type ActionCardProgress = { 
/**
 * Which card is being played.
 */
card: ActionCard, };