// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionCard } from "./ActionCard";
import type { ActionCardPlay } from "./ActionCardPlay";
import type { Expansion } from "./Expansion";

export type ActionCardInfo = { 
/**
 * Which action card this is in regards to.
 */
card: ActionCard, 
/**
 * The 'pretty' name of the action card.
 */
name: string, 
/**
 * Which expansion the action card came from.
 */
expansion: Expansion, 
/**
 * How many copies of the action card that exists in the action card deck.
 */
numInDeck: number, 
/**
 * Human readable text for when the action card can be played.
 */
playText: string, 
/**
 * When the action card can be played.
 */
play: ActionCardPlay, 
/**
 * What effect happens when the action card can be played in human readable format.
 */
effect: string, 
/**
 * The flavor text of the action card.
 */
flavorText: string, };