// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent leader.
 */
export type Agent = "Acamar" | "ArtunoTheBetrayer" | "BerekarBerekon" | "BrotherMilor" | "BrotherMilorCxIII" | "CaptainMendosa" | "CarthOfGoldenSands" | "CleverCleverSsruu" | "DoctorSucaban" | "EmissaryTaivra" | "EvelynDelouis" | "FieldMarshallMercer" | "GarvAndGunn" | "GgrucotoRinn" | "I48S" | "JaeMirKan" | "LetaniOspha" | "NekroMalleon" | "SuffiAn" | "Tellurian" | "TheStillnessOfStars" | "TheThundarian" | "TrillossaAunMirik" | "Tro" | "Umbat" | "ViscountUnlenn" | "Zeu" | "ZeuCxIII" | "XanderAlexinVictoriIII";