// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agenda phase rounds.
 */
export type AgendaRound = "Round1" | "Round2" | "Completed";