// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agenda } from "./Agenda";
import type { ForOrAgainst } from "./ForOrAgainst";
import type { Planet } from "./Planet";
import type { SecretObjective } from "./SecretObjective";
import type { StrategyCard } from "./StrategyCard";

export type AgendaElect = { "electKind": "ForOrAgainst", "value": ForOrAgainst } | { "electKind": "Player", "value": string } | { "electKind": "StrategyCard", "value": StrategyCard } | { "electKind": "Law", "value": Agenda } | { "electKind": "SecretObjective", "value": SecretObjective } | { "electKind": "Planet", "value": Planet } | { "electKind": "PlanetWithTrait", "value": Planet } | { "electKind": "CulturalPlanet", "value": Planet } | { "electKind": "HazardousPlanet", "value": Planet } | { "electKind": "IndustrialPlanet", "value": Planet };