// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoteState } from "./VoteState";

export type AgendaOverrideState = { 
/**
 * The vote state of this agenda override.
 */
voteState: VoteState, };