// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { Faction } from "./Faction";
import type { LeaderAbilityKind } from "./LeaderAbilityKind";

/**
 * Information about an agent leader.
 */
export type AgentInfo = { 
/**
 * [Agent] variant for this agent.
 */
tag: Agent, 
/**
 * Faction that this agent belongs to.
 */
faction: Faction, 
/**
 * Name of the agent.
 */
name: string, 
/**
 * Description of the agents ability.
 */
description: string, 
/**
 * The kind of ability, i.e. whether it's an action or something else.
 */
kind: LeaderAbilityKind, };