// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When, during the agenda phase, an action card can be played.
 */
export type AgendaStagePlay = "WhenReveal" | "AfterReveal" | "AfterYouCastVotes" | "AfterSpeakerVotes" | "AfterElected" | "WhenOutcomeResolve";