// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A type of anomaly.
 */
export type AnomalyType = "AsteroidField" | "Nebula" | "Supernova" | "MuaatSupernova" | "GravityRift";