// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A player color.
 */
export type Color = "Blue" | "Green" | "Red" | "Yellow" | "Black" | "Purple" | "Orange" | "Pink";