// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commander } from "./Commander";
import type { Faction } from "./Faction";
import type { LeaderAbilityKind } from "./LeaderAbilityKind";

/**
 * Information about a commander leader.
 */
export type CommanderInfo = { 
/**
 * [Commander] variant for this commander.
 */
tag: Commander, 
/**
 * Faction that this commander belongs to.
 */
faction: Faction, 
/**
 * Name of the commander.
 */
name: string, 
/**
 * Description of the commanders unlock condition.
 */
unlock: string, 
/**
 * Description of the commanders ability.
 */
description: string, 
/**
 * The kind of ability, i.e. whether it's an action or something else.
 */
kind: LeaderAbilityKind, };