// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commander leader.
 */
export type Commander = "BrotherOmar" | "BrotherOmarCxIII" | "ClaireGibson" | "DartandTai" | "DirzugaRophal" | "ElderQanoj" | "GhomSekkus" | "GilatheSilvertongue" | "IlNaViroset" | "Maban" | "MabanCxIII" | "Magmus" | "NavarchFeng" | "NekroAcidos" | "RearAdmiralFarran" | "RickarRickani" | "RowlSarrig" | "SUlaMentarion" | "SaiSeravus" | "SoAta" | "SuffiAnKeleres" | "TaZern" | "ThatWhichMoldsFlesh" | "TrrakanAunZulok" | "Tungstantus" | "Xuange" | "_2RAM";