// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A coordinate of a tile in the system.
 */
export type Coordinate = { 
/**
 * Which ring the coordinate is in (starting with mecatol rex on 0).
 */
ring: number, 
/**
 * Which position the tile is on starting from the column "above" mecatol rex at 0 and going clockwise around the galaxy.
 */
position: number, 
/**
 * How rotated the tile is.
 */
rotation: number, };