// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Expansions = { prophecyOfKings: boolean, codex1: boolean, codex2: boolean, codex3: boolean, };