// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An expansion for Twilight Imperial 4th edition.
 */
export type Expansion = "Base" | "ProphecyOfKings" | "Codex" | "CodexII" | "CodexIII";