// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Faction } from "./Faction";

export type FactionResponse = { 
/**
 * The faction ID.
 */
faction: Faction, 
/**
 * The name of the faction in 'pretty' format.
 */
name: string, };