// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A playable faction in the game.
 */
export type Faction = "Arborec" | "BaronyOfLetnev" | "ClanOfSaar" | "EmbersOfMuaat" | "EmiratesOfHacan" | "FederationOfSol" | "GhostsOfCreuss" | "L1Z1XMindnet" | "MentakCoalition" | "NaaluCollective" | "NekroVirus" | "SardakkNorr" | "UniversitiesOfJolNar" | "Winnu" | "XxchaKingdom" | "YinBrotherhood" | "YssarilTribes" | "ArgentFlight" | "Empyrean" | "MahactGeneSorcerers" | "NaazRokhaAlliance" | "Nomad" | "TitansOfUl" | "VuilRaithCabal" | "CouncilKeleres";