// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A vote type where players can either vote For or Against.
 */
export type ForOrAgainst = "For" | "Against";