// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A frontier card.
 */
export type FrontierCard = "DerelictVessel" | "EnigmaticDevice" | "GammaRelay" | "IonStorm" | "LostCrew" | "MerchantStation" | "Mirage" | "UnknownRelicFragment" | "DeadWorld" | "EntropicField" | "KeleresShip" | "MajorEntropicField" | "MinorEntropicField";