// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When this frontier card can be played.
 */
export type FrontierCardType = "Action" | "Unhandled";