// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontierCard } from "./FrontierCard";

export type FrontierCardProgress = { 
/**
 * Which card is being played.
 */
card: FrontierCard, };