// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expansions } from "./Expansions";

export type GameSettings = { 
/**
 * The points required to trigger win-condition for this game.
 */
maxPoints: number, 
/**
 * Which expansions are in play this game.
 */
expansions: Expansions, };