// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionCard } from "./ActionCard";
import type { ActionCardInfo } from "./ActionCardInfo";
import type { Agenda } from "./Agenda";
import type { AgendaInfo } from "./AgendaInfo";
import type { Color } from "./Color";
import type { Faction } from "./Faction";
import type { FactionResponse } from "./FactionResponse";
import type { FrontierCard } from "./FrontierCard";
import type { FrontierCardInfo } from "./FrontierCardInfo";
import type { Leader } from "./Leader";
import type { LeaderInfo } from "./LeaderInfo";
import type { Objective } from "./Objective";
import type { ObjectiveInfo } from "./ObjectiveInfo";
import type { Planet } from "./Planet";
import type { PlanetAttachment } from "./PlanetAttachment";
import type { PlanetAttachmentInfo } from "./PlanetAttachmentInfo";
import type { PlanetInfo } from "./PlanetInfo";
import type { Relic } from "./Relic";
import type { RelicInfo } from "./RelicInfo";
import type { System } from "./System";
import type { TechInfo } from "./TechInfo";
import type { Technology } from "./Technology";

export type GameOptions = { 
/**
 * The minimum number of players allowed for the game.
 */
minPlayers: number, 
/**
 * The maximum number of players allowed for the game.
 */
maxPlayers: number, 
/**
 * What colors players are allowed to have.
 */
colors: Array<Color>, 
/**
 * What factions exist within the game.
 */
factions: Array<FactionResponse>, 
/**
 * What systems exists in the game.
 */
systems: Array<System>, 
/**
 * What technologies exist in the game.
 */
technologies: { [key in Technology]: TechInfo }, 
/**
 * What planets exist in the game.
 */
planetInfos: { [key in Planet]: PlanetInfo }, 
/**
 * What planet attachments exist in the game.
 */
planetAttachments: { [key in PlanetAttachment]: PlanetAttachmentInfo }, 
/**
 * What objectives exist in the game.
 */
objectives: { [key in Objective]: ObjectiveInfo }, 
/**
 * What action cards exist in the game.
 */
actionCards: { [key in ActionCard]: ActionCardInfo }, 
/**
 * What agendas exist in the game.
 */
agendas: { [key in Agenda]: AgendaInfo }, 
/**
 * What leaders exist in the game.
 */
leaders: { [key in Leader]: LeaderInfo }, 
/**
 * Map from all factions in the game to the leaders of that faction.
 */
leadersByFaction: { [key in Faction]: Array<Leader> }, 
/**
 * What frontier cards exists in the game.
 */
frontierCards: { [key in FrontierCard]: FrontierCardInfo }, 
/**
 * What relics exists in the game.
 */
relics: { [key in Relic]: RelicInfo }, };