// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expansions } from "./Expansions";

export type GameSettings = { maxPoints: number, expansions: Expansions, };