// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hero leader.
 */
export type Hero = "AdjudicatorBaal" | "AhkSylSiven" | "AiroShirAur" | "ConservatorProcyon" | "DannelOfTheTenth" | "DannelOfTheTenthCxIII" | "DarktalonTreilla" | "GurnoAggero" | "HarkaLeeds" | "HarrughGefhara" | "HeshAndPrit" | "IpswitchLooseCannon" | "ItFeedsOnCarrion" | "JaceX4thAirLegion" | "KuuasiAunJalatai" | "KyverBladeAndKey" | "LetaniMiasmiala" | "MathisMathinus" | "MirikAunSissiri" | "OdlynnMyrr" | "RiftwalkerMeian" | "RinTheMastersLegacy" | "ShvalHarbinger" | "TheHelmsman" | "TheOracle" | "UlTheProgenitor" | "UnitDsgnFlayesh" | "XxekirGrom" | "XxekirGromCxIII";