// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coordinate } from "./Coordinate";

/**
 * A position of a tile in the game.
 */
export type HexPosition = "OutsideGalaxy" | { "Pos": Coordinate };