// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { Commander } from "./Commander";
import type { Hero } from "./Hero";

export type Leader = Agent | Commander | Hero;