// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Leader } from "./Leader";

export type LeaderProgress = { "action": "nothing", leader: Leader, };