// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a leader ability, i.e. if it's an Action, etc.
 */
export type LeaderAbilityKind = "Action" | "Other";