// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HexMap } from "./HexMap";

export type MapData = { 
/**
 * The hex map for the game.
 */
hexMap: HexMap, 
/**
 * The system that contains mirage (if any).
 */
mirageSystem: string | null, };