// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MiltyInformation } from "./MiltyInformation";
import type { Planet } from "./Planet";

export type MapData = { 
/**
 * Map information relevant to games imported from milty draft.
 */
miltyInformation: MiltyInformation | null, 
/**
 * Which planets (if any) has been destroyed by the stellar converter.
 */
stellarConverterDestroyedPlanets: Array<Planet>, };