// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Faction } from "./Faction";

export type NewPlayer = { 
/**
 * The name of the player.
 */
name: string, 
/**
 * Which faction the player is playing.
 */
faction: Faction, 
/**
 * Which color the player has.
 */
color: Color, };