// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicObjective } from "./PublicObjective";
import type { SecretObjective } from "./SecretObjective";

export type Objective = PublicObjective | SecretObjective;