// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A phase of the game (including some that exist only for technical reasons).
 */
export type Phase = "Creation" | "Setup" | "Strategy" | "Action" | "StrategicAction" | "TacticalAction" | "ActionCardAction" | "FrontierCardAction" | "RelicAction" | "EndActionTurn" | "Status" | "Relics" | "Agenda";