// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A planetary trait.
 */
export type PlanetTrait = "Cultural" | "Hazardous" | "Industrial";