// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expansion } from "./Expansion";
import type { PlanetTrait } from "./PlanetTrait";
import type { TechCategory } from "./TechCategory";

export type PlanetInfo = { 
/**
 * The name of the planet.
 */
name: string, 
/**
 * Which, if any, planet trait the planet has.
 */
planetTrait: PlanetTrait | null, 
/**
 * Which, if any, technology bonus the planet has.
 */
techSpecialty: TechCategory | null, 
/**
 * How many resources the planet has.
 */
resources: number, 
/**
 * How much influence the planet provides.
 */
influence: number, 
/**
 * Which expansion the planet belongs to.
 */
expansion: Expansion, 
/**
 * Weather the planet is legendary or not.
 */
isLegendary: boolean, };