// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Relic } from "./Relic";

export type RelicProgress = { 
/**
 * The relic whose action is being taken.
 */
relic: Relic, };