// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Relic = "DominusOrb" | "MawOfWorlds" | "ScepterOfEmelpar" | "ShardOfTheThrone" | "StellarConverter" | "TheCodex" | "TheCrownOfEmphidia" | "TheCrownOfThalnos" | "TheObsidian" | "TheProphetsTears" | "DynamisCore" | "JrXs4550" | "NanoForge";