// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When this relic can be used.
 */
export type RelicPlay = "Action" | "Agenda" | "Possession" | "AfterTactical" | "Unhandled";