// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Planet } from "./Planet";

export type ScorableAgenda = { "electableAgendaKind": "HolyPlanetOfIxth", "value": { 
/**
 * The planet in question.
 */
planet: Planet, } } | { "electableAgendaKind": "ShardOfTheThrone", "value": { 
/**
 * The player that currently has the card.
 */
player: string, } } | { "electableAgendaKind": "TheCrownOfEmphidia", "value": { 
/**
 * The player that currently has the card.
 */
player: string, } } | { "electableAgendaKind": "Mutiny", "value": { 
/**
 * The players that voted for this agenda.
 */
playersThatVotedFor: Array<string>, 
/**
 * Whether the alternative 'for' won or not.
 */
forWon: boolean, } } | { "electableAgendaKind": "SeedOfAnEmpire", "value": { 
/**
 * The players that got a point.
 */
playersElected: Array<string>, } } | { "electableAgendaKind": "PoliticalCensure", "value": { 
/**
 * The player in question.
 */
player: string, } };