// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StrategicPrimaryProgress } from "./StrategicPrimaryProgress";
import type { StrategicSecondaryProgress } from "./StrategicSecondaryProgress";
import type { StrategyCard } from "./StrategyCard";

export type StrategicProgress = { 
/**
 * The strategy card being played.
 */
card: StrategyCard, 
/**
 * What, if any, progress has been made for the primary part of the strategy card.
 */
primary: StrategicPrimaryProgress | null, 
/**
 * What secondary actions other players have taken.
 */
otherPlayers: { [key: string]: StrategicSecondaryProgress }, };