// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A strategy card.
 */
export type StrategyCard = "Leadership" | "Diplomacy" | "Politics" | "Construction" | "Trade" | "Warfare" | "Technology" | "Imperial";