// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Technology } from "./Technology";

/**
 * The progress of the secondary portion of a strategy card.
 */
export type StrategicSecondaryProgress = "Leadership" | "Diplomacy" | "Politics" | "Construction" | "Trade" | "Warfare" | { "Technology": { 
/**
 * What tech was taken.
 */
tech: Technology, } } | "Imperial" | "Skipped";