// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expansion } from "./Expansion";
import type { Planet } from "./Planet";
import type { SystemType } from "./SystemType";
import type { WormHoleType } from "./WormHoleType";

export type System = { 
/**
 * A unique id for the system.
 */
id: string, 
/**
 * What type of system this is.
 */
systemType: SystemType, 
/**
 * What expansion this system belongs to.
 */
expansion: Expansion, 
/**
 * Which planets exist in this system.
 */
planets: Array<Planet>, 
/**
 * What wormhole types exists in this system.
 */
wormholes: Array<WormHoleType>, };