// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnomalyType } from "./AnomalyType";
import type { Faction } from "./Faction";

/**
 * A type of system.
 */
export type SystemType = { "Anomaly": AnomalyType } | "Hyperlane" | "Normal" | { "HomeSystem": Faction };