// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Planet } from "./Planet";
import type { PlanetAttachment } from "./PlanetAttachment";

export type TacticalProgress = { 
/**
 * What system was activated, if any.
 */
activatedSystem: string | null, 
/**
 * Which planets have been taken this far and the player who owned them previously (if any).
 */
takenPlanets: { [key in Planet]: string | null }, 
/**
 * What planet attachments have been selected for the taken planets.
 * NOTE: Does not include attachments kept when taken from another player.
 */
planetAttachments: { [key in Planet]: PlanetAttachment }, };