// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What category the tech belongs to.
 */
export type TechCategory = "Biotic" | "Propulsion" | "Cybernetic" | "Warfare";