// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Faction } from "./Faction";

/**
 * Weather the game is general or faction specific.
 */
export type TechOrigin = "Base" | { "Faction": Faction };