// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TechCategory } from "./TechCategory";

/**
 * What type of tech this is.TS_RS_EXPORT_DIR
 */
export type TechType = { "Category": TechCategory } | "UnitUpgrade";