// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HexPosition } from "./HexPosition";

/**
 * A tile in play.
 */
export type Tile = { 
/**
 * The id of the system.
 */
system: string, 
/**
 * Where it exists on the galactic map.
 */
position: HexPosition, };