// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What type of wormhole this is.
 */
export type WormHoleType = "Alpha" | "Beta" | "Gamma" | "Delta";