[package]
name = "ti_helper_map_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
eyre = "0.6.8"
log = "0.4.20"

[dependencies.ti_helper_game]
path = "../game"
